/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component, useState} from 'react';
import {Platform, StyleSheet, Text, View} from 'react-native';
import {PersonasAvatar} from 'react-native-personas-avatar';

export default function App() {
  const [characters, setCharacters] = useState(
    'body2|eyes2|facialHair4|hair4|mouth7|nose3|bgc1|sc4|hc7|fhc1|bc2',
  );
  return (
    <View style={styles.container}>
      <PersonasAvatar
        characters={characters}
        onNewCharacters={characters => {
          setCharacters(characters);
        }}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
